{"name": "Test login with incorrect login credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/oleg/PycharmProjects/bdd/.venv/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/oleg/PycharmProjects/bdd/.venv/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 24, in step_impl\n    log.error('Login button clicked')\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1506, in error\n    self._log(ERROR, msg, args, **kwargs)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1624, in _log\n    self.handle(record)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1634, in handle\n    self.callHandlers(record)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1696, in callHandlers\n    hdlr.handle(record)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 968, in handle\n    self.emit(record)\n  File \"/home/oleg/PycharmProjects/bdd/logs/logs_file.py\", line 18, in emit\n    self.log(record.levelname, record.getMessage())\n  File \"/home/oleg/PycharmProjects/bdd/logs/logs_file.py\", line 15, in log\n    assert False\n"}, "steps": [{"name": "log(INFO ====== WebDriver manager ======)", "status": "passed", "start": 1714744579174, "stop": 1714744579174}, {"name": "log(INFO Get LATEST chromedriver version for google-chrome)", "status": "passed", "start": 1714744579212, "stop": 1714744579212}, {"name": "log(INFO Get LATEST chromedriver version for google-chrome)", "status": "passed", "start": 1714744579332, "stop": 1714744579332}, {"name": "log(INFO Driver [/home/oleg/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver] found in cache)", "status": "passed", "start": 1714744579451, "stop": 1714744579451}, {"name": "When input wrong credentials", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/oleg/PycharmProjects/bdd/.venv/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/oleg/PycharmProjects/bdd/.venv/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 24, in step_impl\n    log.error('Login button clicked')\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1506, in error\n    self._log(ERROR, msg, args, **kwargs)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1624, in _log\n    self.handle(record)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1634, in handle\n    self.callHandlers(record)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 1696, in callHandlers\n    hdlr.handle(record)\n  File \"/usr/lib/python3.10/logging/__init__.py\", line 968, in handle\n    self.emit(record)\n  File \"/home/oleg/PycharmProjects/bdd/logs/logs_file.py\", line 18, in emit\n    self.log(record.levelname, record.getMessage())\n  File \"/home/oleg/PycharmProjects/bdd/logs/logs_file.py\", line 15, in log\n    assert False\n"}, "steps": [{"name": "log(ERROR Login button clicked)", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/oleg/PycharmProjects/bdd/logs/logs_file.py\", line 15, in log\n    assert False\n"}, "start": 1714744582551, "stop": 1714744582551}], "start": 1714744579827, "stop": 1714744582552}, {"name": "Then error message will come", "status": "skipped", "start": 1714744582620, "stop": 1714744582620}], "start": 1714744579174, "stop": 1714744582620, "uuid": "ddb01f00-3d23-41f6-80d9-c5a127e701b2", "historyId": "9c564e50d5edb9b715f32e133cc41df4", "fullName": "Facebook login functionality: Test login with incorrect login credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "logincase"}, {"name": "feature", "value": "Facebook login functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}